# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8039deaaf2e4ebc98cda0829a5bf8add518d18eb9a56e80bcde600764706beba48e5420992231b9b08664b62ff9c17dd06d24286612334d17fe209ddee71b90e

test:
  secret_key_base: b81715890e896031c024f4a9bf8746abaca5413e6503bf37bcac7e81b8a703a6e0f680cf81e34ae2a215aa8cde896d5a9646ce4384d05977decbdfe5578523a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
